#!/bin/bash

system_type=$(uname -s)

echo "Updating the yadm repo origin URL"
yadm remote set-url origin "git@github.com:julon/dotfiles.git"

if [ "$system_type" = "Darwin" ]; then

  # Update macOS apps
  echo 'Upgrading macOS apps...'
  sudo softwareupdate -i -a

  # Install all homebrew packages inside Brewfile
  echo 'Installing/Upgrading brew apps...'

  # Check for Homebrew Installation
  if ! which brew > /dev/null; then
      # Install Homebrew
      /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi;

  # Update Homebrew
  brew update

  if [ -f "$HOME/.Brewfile" ]; then
    echo "Updating homebrew bundle"
    # Install everything inside Brewfile
    brew bundle --global --verbose
     
    # Remove installed formulae not in Brewfile
    brew bundle cleanup --global --force
  fi

  # Remove outdated versions from the cellar
  brew cleanup

  # Switch to using brew-installed bash as default shell
  if ! fgrep -q '/usr/local/bin/bash' /etc/shells; then
    echo '/usr/local/bin/bash' | sudo tee -a /etc/shells;
    chsh -s /usr/local/bin/bash;
  fi;

  # possibly add something here to ensure iTerm2 is installed using Homebrew
  # cask like in the previous example
  if [ ! -d "$HOME/.config/iterm2" ]; then
    echo "Setting iTerm preference folder"
    defaults write com.googlecode.iterm2 PrefsCustomFolder "$HOME/.config/iterm2"
  fi
  
  # update node global packages
  npm install npm -g
  npm update -g

  # Update ruby packages
  gem update --system
  gem update
  gem cleanup

  # Install vim package manager Dein
  if [ ! -d "$HOME/.vim/dein/repos/github.com/Shougo/dein.vim" ]; then
    git clone https://github.com/Shougo/dein.vim.git $HOME/.vim/dein/repos/github.com/Shougo/dein.vim
  fi
  
  # Install neovim python/ruby support
  pip3 install neovim
  gem install neovim

  if command -v vim >/dev/null 2>&1; then
    echo "Bootstrapping Vim"
    nvim '+"call dein#install()"' '+qall'
  fi
fi